import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/components/ToastProvider";
import { GlobalLoadingProvider } from "@/components/GlobalLoading";
import { Sidebar } from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalLoadingProvider>
          <div className="flex min-h-screen bg-[--color-background] text-[--color-foreground]">
            <Sidebar />
            <div className="flex-1 bg-[--color-surface]">{children}</div>
          </div>
          <ToastProvider />
        </GlobalLoadingProvider>
      </body>
    </html>
  );
}
